### ISSUE TITLE
В windows при открытии закладки "Alure report" происходит ошибка сервлета при установке заголовков http ответа.

### ISSUE THREAD

**Issue by mrscylla** [allure-framework/allure-bamboo#109]
Валится в файле: allure-bamboo/src/main/java/io/qameta/allure/bamboo/AllureReportServlet.java в процедуре setResponseHeaders. Убрал нормализацию пути Path.get() и заработало.

Я не java программист, поэтому не уверен как правильно и не могу направить пуллреквест с этим кодом.

```

private void setResponseHeaders(HttpServletResponse response, String fileUrl) throws IOException {

        try {
            response.setStatus(HttpServletResponse.SC_OK);
            final URI file = new URL(fileUrl).toURI();
            //final String mimeType = ofNullable(getServletContext().getMimeType(fileUrl)).orElse(Files.probeContentType(Paths.get(file.getPath())));
            final String mimeType = getServletContext().getMimeType(fileUrl);
            final String charsetPostfix = of("application", "text").anyMatch(mimeType::contains) ? ";charset=utf-8" : "";
            response.setHeader("Content-Type", mimeType + charsetPostfix);
            //response.setHeader("Content-Disposition", "inline; filename=\"" + Paths.get(file.getPath()).getFileName().toString() + "\"");
            response.setHeader("Content-Disposition", "inline; filename=\"" + fileUrl + "\"");

        } catch (URISyntaxException e) {
            // should never happen
            throw new RuntimeException(e);
        }
    }

```
![image](https://user-images.githubusercontent.com/402495/74406802-a79ac400-4e41-11ea-8983-c8bfb4a810c9.png)

_Originally posted by @mrscylla in https://github.com/allure-framework/allure-bamboo/issues/88#issuecomment-585568572_

**Comment by CrazyMoonkin** [comment]
Приветствую! 
Я бы посоветовал посмотреть, что возвращает метод `getArtifactUrl(request, response)`. Где-то он неправильно формирует URL до артефакта. Подозреваю, что виноват метод getLocalStorageURL, т.к. он однажды уже грешил таким.

![изображение](https://user-images.githubusercontent.com/30863968/81541177-656b1b00-937b-11ea-943d-d46da69553ce.png)

**Comment by eyemana** [comment]
I fixed this problem on my installation by using a UNC path instead of a windows file path in the Bamboo Administration >> Manage Apps >> Allure Report >> Allure Local Storage field.  

I originally had it set to 'C:\Atlassian\Bamboo\temp'  but this got the error for the ':' at index 2.
I set it to '\Atlassian\Bamboo\temp' and it still got the same error!  I guess the 'C:' got added behind the scenes.

I set it to '\\\myserver\c$\Atlassian\Bamboo\temp' and that fixed the problem.
