### ISSUE TITLE
Timeout increasing

### ISSUE THREAD

**Issue by epenzev** [allure-framework/allure-bamboo#112]
Hi,

I've got the following error while creating an Allure report:

`Caused by: org.buildobjects.process.TimeoutException: Process '/bin/bash /tmp/allure-executable-2.4.1/binary/bin/allure generate -o /home/bamboo/Atlassian/bamboo/temp/1581939619855-1/report /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/24523291-c0d4-4971-99dd-2187489640a1 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/4b2b12fb-9686-4395-94a0-0e25546fc647 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/55296fd0-c6bf-4f99-87d1-5bb03b3c9f9f /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/8645afb3-0fa1-43b7-9577-bde8f5dd92b1 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/2ad75a36-a637-4349-a5dd-17679d1349c4 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/5c19ae83-3e1b-440c-b9b7-ecb36e22266e /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/b5414796-55a6-4d5b-aa1c-acbcb49ce3b4 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/24e8fafd-c890-4d5a-ba49-e3efb68202c2 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/a390a761-cab9-4a9f-9d4d-b927311f17a2 /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/fcbb130e-e2fb-4d59-9e1c-875df1749cda /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/6884f2b3-5940-496c-a4a1-6f602ec757cc /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/6a40303a-5146-4cf4-831e-a5f19b9cb12a /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/8908098e-16ce-48fe-a1ff-edb49bb3070b /home/bamboo/Atlassian/bamboo/temp/1581939619855-0/451af581-4475-4647-a4ea-5a18b9697279' timed out after 60000ms.`

I couldn't find any setting that would increase the timeout value. Furthermore, in the file allure.properties I put 'allure.serve.timeout=300' but that didn't help either.

How else I could increase it?

Thanks

**Comment by vmilena** [comment]
I ran into this same issue, is there a way to solve this?

**Comment by vbragin** [comment]
unreproducible: please use the newest version (for plugin and report)
