### ISSUE TITLE
Allure generating error if there's no access to maven central.

### ISSUE THREAD

**Issue by dulldisney** [allure-framework/allure-bamboo#12]
Due to security reasons our bamboo has no access to maven central, but we have local artifactory. Is there any way to specify it to allure task, cause now i see next:

```
-----------
simple  24-Aug-2016 15:57:27    Allure Task
simple  24-Aug-2016 15:57:27    -----------
simple  24-Aug-2016 15:57:27    Trying to generate Allure 1.4.16 using %path_here% as base directory with pattern = **/allure-results/
simple  24-Aug-2016 15:57:27    Allure data will be saved to %path_here%
simple  24-Aug-2016 15:57:27    Processing Allure XML files
error   24-Aug-2016 15:57:57    Caught an exception while generating Allure
error   24-Aug-2016 15:57:57    ru.yandex.qatools.allure.report.AllureReportBuilderException: org.eclipse.aether.collection.DependencyCollectionException: Failed to read artifact descriptor for ru.yandex.qatools.allure:allure-report-data:jar:1.4.16

...

error   24-Aug-2016 15:57:57    Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact ru.yandex.qatools.allure:allure-report-data:pom:1.4.16 from/to  (http://repo1.maven.org/maven2/): Connect to repo1.maven.org:80 timed out
```

I have to say that we used TeamCity as CI system before and didn't face this problem. Project and it's pom stayed the same. Is there any solution to this problem?

**Comment by vania-pooh** [comment]
This plugin needs to be refactored in order to use newer report generation engine. ETA is unknown.

**Comment by dulldisney** [comment]
Ok, thanks for responce.

**Comment by dabos** [comment]
@vania-pooh if still no eta can you give more details as to what needs to be refactored ?

**Comment by baev** [comment]
@dabos hi!

We should use `allure-commandline` instead of `ReportBuilder` like Jenkins plugin did. So we need to be able to load commandline like external tool (it would be nice to have an ability to use different versions of commandline in different build), and then run it during build step.

**Comment by eroshenkoam** [comment]
Fixed in latest version.
