### ISSUE TITLE
Release bamboo plugin

### ISSUE THREAD

**Issue by sseliverstov** [allure-framework/allure-bamboo#16]

**Comment by rmarinsky** [comment]
Hi, in docs have no info abput field "Version" in allure bamboo plugin
https://docs.qameta.io/allure/2.0/#_bamboo
But i see: http://i.imgur.com/QB0qTeO.png
What version i need to set?

**Comment by sseliverstov** [comment]
@eroshenkoam it is done, I right?

**Comment by rmarinsky** [comment]
@sseliverstov yes, it's done
