### ISSUE TITLE
Add ability to utilize allure plugin behind firewall

### ISSUE THREAD

**Issue by aolson58** [allure-framework/allure-bamboo#17]
Right now, when using this plugin out of the box, I am unable to download the required dependencies in order to do the report processing
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact ru.yandex.qatools.allure:allure-report-data:pom:1.4.16 from/to  (http://repo1.maven.org/maven2/): Connect to repo1.maven.org:80 timed out
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:80 timed out

Could be because we need to feed proxy information in order to reach out to any maven repositories. 

I saw in an earlier issue there was talk about reworking the plugin to use the command line versus pulling down the report builder? 

Or is there a way you guys know to do this in current state?

**Comment by baev** [comment]
@aolson58 hi!

We rewrote allure-bamboo plugin, so now it isn't require internet connection to build the report. See https://github.com/allure-framework/allure-bamboo/pull/14

**Comment by aolson58** [comment]
Has that been released yet or is it still under review?

**Comment by baev** [comment]
Yep, it still under review, but if you like so you can try it out and give us a feedback

**Comment by eroshenkoam** [comment]
Fixed in latest version
