### ISSUE TITLE
Allure plugin not working in bamboo

### ISSUE THREAD

**Issue by nismalho** [allure-framework/allure-bamboo#196]
Hi Team ,
 
We got a request from one of our bamboo user to install the “Allure Report” plugin in bamboo .  User want this plugin to execute specflow automation html report from bamboo 
So we have installed the plugin in our stage (lower) environment before going to the production environment . But when we install the plugin in Manage App the version is showing 1.11.0 . But in the shared agent capability the version is showing 2.7.0 . 
Also we have tried the manually installation using a zip file of version 2.8.0 and adding the capability path in the agent but it is also not working . We are using the following documentation to install :
https://docs.qameta.io/allure/#_bamboo
Also while following the above mentioned docs we are not able to see the configurations (Point no 13.4.2.7 in the above documentation ) . We are getting the following error :
 ``
02-Mar-2021 08:16:31    Error occurred while running Task 'Coopertier Allure results(12)' of type io.qameta.allure.allure-bamboo:allureReportTask.
02-Mar-2021 08:16:31    java.lang.NoSuchMethodError: com.atlassian.bamboo.build.logger.BuildLogger.addBuildLogHeader(Ljava/lang/String;Z)Ljava/lang/String;
02-Mar-2021 08:16:31            at io.qameta.allure.bamboo.AllureReportTask.execute(AllureReportTask.java:23)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:321)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:256)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:321)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:116)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:73)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:184)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:156)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:130)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:118)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:124)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.lambda$start$0(DefaultBuildAgent.java:108)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
02-Mar-2021 08:16:31            at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
02-Mar-2021 08:16:31            at java.lang.Thread.run(Thread.java:748)
 `
![Agent capabilities](https://user-images.githubusercontent.com/80947428/111749489-e1958f80-88b7-11eb-8b08-550614f4f1d2.PNG)
![allure configuration in administration](https://user-images.githubusercontent.com/80947428/111749493-e2c6bc80-88b7-11eb-8ba0-ff4d63c2e5dc.PNG)
![allure configuration in others](https://user-images.githubusercontent.com/80947428/111749495-e35f5300-88b7-11eb-8ade-ee84ee426232.PNG)
![allure configuration in task](https://user-images.githubusercontent.com/80947428/111749498-e3f7e980-88b7-11eb-92c1-0227852d5b17.PNG)
![Allure report error](https://user-images.githubusercontent.com/80947428/111749500-e3f7e980-88b7-11eb-917c-39ac841d830a.PNG)

`
 
Also screenshot of the error , configuration and agent specific capabilities screenshot is attached with this ticket .
 
Please let us know if we are doing any configuration wrong  . Also is there any other plugin which can we used instead of Allure to fulfil the users requirements.
 
 
Bamboo Version : 7.0.4
 
Please let us know if you need any other information form my side .
 
Thanks
Nishtha Malhotra

**Comment by nismalho** [comment]
HI Team ,

Any update on this .

Thanks
Nishtha Malhotra

**Comment by nismalho** [comment]
Hi Team ,

Please update us how can we resolve this .

Thanks
Nishtha Malhotra

**Comment by baflQA** [comment]
Hi, try to change the "Allure bintray base url" to ```https://github.com/allure-framework/allure2/releases/download/```

**Comment by vbragin** [comment]
for versions >= 2.13.1
Try to change the "Allure binary base url" to https://github.com/allure-framework/allure2/releases/download/
For versions <= 2.13.0
Try to change the "Allure binary base url" to https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline

If you install it manually set the execution path to:
/some/path/
And make sure that the full path will be like:
/some/path/binary/bin/allure
