### ISSUE TITLE
Tests sort by order of execution doesn't exist

### ISSUE THREAD

**Issue by zavrakv** [allure-framework/allure-bamboo#199]
Hello guys! 

In this plugin for bamboo there is no possibility to sort tests by order of execution
For instance, here are the results generated by npm allure package locally:

![tempsnip](https://user-images.githubusercontent.com/15162920/113289158-896b7e00-92f8-11eb-950e-af5ce1ccec79.png)

As you can see, I can sort by "order" here. But this option doesn't exist in the bamboo plugin:

![tempsnip2](https://user-images.githubusercontent.com/15162920/113289531-0139a880-92f9-11eb-88aa-702700953b46.png)

Is there a possibility to enable this type of ordering somehow? It is crucial for some of our tests

Thanks in advance :)

**Comment by vbragin** [comment]
Bamboo plugin uses the "allure execution" to generate a report.
https://github.com/allure-framework/allure2
Looks like to generate local report you are using the latest version of allure execution.
Use the latest version for your execution in the allure to generate the report.
https://docs.qameta.io/allure/#_bamboo
