### ISSUE TITLE
Unable to use allure-for-bamboo task in the pipeline

### ISSUE THREAD

**Issue by sameerkarmarkar** [allure-framework/allure-bamboo#207]
Hello,

I installed allure-for-bamboo task. But I see a depricated notification on the task logo.

Moreover, when I try to configure the task, I don't see any configuration fields that are mentioned on the standard documentation. When executed, the task does not work and the console outputs a message saying "this plugin is a sham".

Is this plugin indeed not working at all and not expected to be used anymore?
![Screen Shot 2021-04-26 at 10 24 17](https://user-images.githubusercontent.com/72141544/116052609-13013800-a67a-11eb-9b76-12cac56de2cd.png)
![Screen Shot 2021-04-26 at 10 23 55](https://user-images.githubusercontent.com/72141544/116052618-14cafb80-a67a-11eb-9afe-30d8cda54c29.png)

**Comment by vbragin** [comment]
Try to set it up according the documentation:

https://docs.qameta.io/allure/#_bamboo
