### ISSUE TITLE
Bamboo plugin installation failing on supported version of Bamboo

### ISSUE THREAD

**Issue by jandersonusf** [allure-framework/allure-bamboo#236]
The latest version 1.11.0 of the plugin states that our version of Bamboo 6.10.4 should work. However when installing we get an error (logs attached). We have contacted Atlassian Support (email text attached) and they were able to replicate the error on the same version of Bamboo. Can you update the plugin or at least the supported versions of the latest version to avoid this confusion?

[email.txt](https://github.com/allure-framework/allure-bamboo/files/6925448/email.txt)

[logs.txt](https://github.com/allure-framework/allure-bamboo/files/6925609/logs.txt)

**Comment by jasonbutler22** [comment]
I am also seeing the same error when I install the allure-bamboo plugin on bamboo 6.3.0

**Comment by battmush** [comment]
I ran into the same problem last night, and discovered that it is due to the published 1.11.0/1.12.0 were built for Java 9+.  Our Bamboo instance is running on Java 8, so of course barfs when trying to deploy the plugin.

If I could find the right branch that 1.12.0 was built from I'd rebuild it myself, but the master is currently at 1.11.0-SNAPSHOT.  That's not in any way encouraging.

**Comment by battmush** [comment]
For any doubt on that: the pom *does* indicate <compiler.version>1.8</compiler.version>, however, if you take the jar file and crack it open:

$ wget https://github.com/allure-framework/allure-bamboo/releases/download/1.12.0/allure-bamboo-1.12.0.jar
$ unzip allure-bamboo-1.12.0.jar
$ file module-info.class
module-info.class: compiled Java class data, version 53.0

version 53.0 == Java SE 9

see: [Java class file](https://en.wikipedia.org/wiki/Java_class_file#General_layout)

**Comment by battmush** [comment]
From my testing, it was the change from net.sf.json-lib to com.fasterxml.jackson.core in 1.11.0 that is causing this issue.  

https://github.com/allure-framework/allure-bamboo/compare/1.10.0...1.11.0

Reverting the change in the pom.xml and AbstractAddInfo.java removes the inclusion of the module-info.class in the allure-bamboo.jar, and the jar successfully deploys on Bamboo 6.9.1 running on Java 1.8.  I'll leave it to the module authors to officially address this.

**Comment by vbragin** [comment]
@battmush this is correct, will be restore in future release.

The versions 1.11 and 1.12 in not supported for versions < 7
