### ISSUE TITLE
Failed to find Allure executable by name Allure 2.3.1

### ISSUE THREAD

**Issue by sivasusheendar** [allure-framework/allure-bamboo#239]
1. We followed all steps mentioned here :  https://docs.qameta.io/allure/#_bamboo
2.  But we are getting below error :  **java.lang.RuntimeException: Failed to find Allure executable by name Allure 2.3.1**
 Our expectation is if executable is missing in mentioned path it will get downloaded from  "Allure binary base url(required)".
But below URL throw forbidden message : https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/
3. Added Allure capability in Agent level and Server level both.

Please help us on solving this issue.

**Comment by sivasusheendar** [comment]
Any info on this issue ?

**Comment by vbragin** [comment]
1) As workout for this issue download allure binary from:

https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip

put it in some folder and unzip it.
2) Create new or edit default executable 
use the path to the folder where you unzip the allure

3)make sure the path to executable binary is like pattern:
<path to executable>/binary/bin/<allure or allure.bat>

For example 
If the path in the executable: /Users/newuser/Downloads/allure-2.17.2/
The real path of file system is: /Users/newuser/Downloads/allure-2.17.2/binary/bin/allure

4) use this executable in plan config
===================

**Comment by vbragin** [comment]
executable name should be like:
allure-2.17.2 or allure-2.3.1
It is important to parse this string.

The "Allure binary base url" should be like 
https://github.com/allure-framework/allure2/releases/download

If it is not help use:
===================
As workout for this issue download allure binary from:
https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip

put it in some folder and unzip it.
2) Create new or edit default executable
use the path to the folder where you unzip the allure

3)make sure the path to executable binary is like pattern:
/binary/bin/

For example
If the path in the executable: /Users/newuser/Downloads/allure-2.17.2/
The real path of file system is: /Users/newuser/Downloads/allure-2.17.2/binary/bin/allure

use this executable in plan config
===================

**Comment by krisavi** [comment]
> executable name should be like: allure-2.17.2 or allure-2.3.1 It is important to parse this string.
> 
> The "Allure binary base url" should be like https://github.com/allure-framework/allure2/releases/download
> 
> If it is not help use:
> 
> As workout for this issue download allure binary from: https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip
> 
> put it in some folder and unzip it. 2) Create new or edit default executable use the path to the folder where you unzip the allure
> 
> 3)make sure the path to executable binary is like pattern: /binary/bin/
> 
> For example If the path in the executable: /Users/newuser/Downloads/allure-2.17.2/ The real path of file system is: /Users/newuser/Downloads/allure-2.17.2/binary/bin/allure
> 
> use this executable in plan config

Sorry for posting on so old closed ticket, but this information about the path should be in documentation.
