### ISSUE TITLE
Allure history disappeared after testless/buildspec build

### ISSUE THREAD

**Issue by SaFiT** [allure-framework/allure-bamboo#272]
I ran into a problem that after a build that does not contain test cases (Broken) or build sepcs Allure does not display the history.
Example:
![image](https://user-images.githubusercontent.com/22996119/189670130-34f34ff9-4f27-47e8-a642-5fff059b06d3.png)
Allure report of 490 build doesn't contain history.
Seems that root cause in allure-bamboo plugin:
When build is done allure trying to define last allure report with history and it implemented by calling URL 
```
format("%s/plugins/servlet/allure/report/%s/%s/history/%s",
                getBambooBaseUrl(), planKey, buildId, fileName)
```
if returned 200, it means that build contain history and allure will copy artifacts from build, but if build is testless allure still returns 200 on above URL and trying to copy history from build without history.

Allure-bamboo plugin version: 1.14.0

**Comment by tomkeiev** [comment]
The same issue occurs when deleting plan run results. The tab 'Allure Report' isn't shown but the report is generated and accessible via the URL

**Comment by vbragin** [comment]
Please try 1.19.1 version
