### ISSUE TITLE
Incorrect pom.xml file. Issue with bamboo

### ISSUE THREAD

**Issue by dvyatkov** [allure-framework/allure-bamboo#287]
Hello! 

We are seeing a problem with our bamboo instances. 
On each of them, we had a problem with hanging agents in the status 'idle' and 'pending'. Atlassian support has indicated that there is a problem with the **atlassian-spring-scanner-annotation** and the user-installed plugin. How the plugin-reason was indicated by Allure

Below is the Atlassian support response:
I have checked the code of these 2 Allure plugins as well and found the configuration related to the dependency atlassian-spring-scanner-annotation is configured as <scope>compile</scope> instead of <scope>provided</scope>. Please see the below for the same:

**Allure-ee-bamboo** :

```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-ee-bamboo</artifactId>
    <version>4.0.0</version>

    <organization>
        <name>Qameta Software</name>
        <url>https://github.com/qameta</url>
    </organization>

    <name>Allure EE for Bamboo</name>
    <description>This is the Allure EE plugin for Atlassian Bamboo.</description>
    <packaging>atlassian-plugin</packaging>
...
<dependency>
            <groupId>com.atlassian.plugin</groupId>
            <artifactId>atlassian-spring-scanner-annotation</artifactId>
            <version>${atlassian.spring.scanner.version}</version>
            <scope>compile</scope>
        </dependency>
```
**Allure for Bamboo** :

```
<?xml version="1.0" encoding="UTF-8"?>

<!--suppress VulnerableLibrariesLocal -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-bamboo</artifactId>
    <version>1.15.0</version>
    <name>Allure for Bamboo</name>
    <description>Allure reports right in deployment plans in Bamboo</description>
    <packaging>atlassian-plugin</packaging>
    <organization>
        <name>Allure Framework</name>
        <url>https://github.com/allure-framework</url>
    </organization>
....
 <dependency>
            <groupId>com.atlassian.plugin</groupId>
            <artifactId>atlassian-spring-scanner-annotation</artifactId>
            <version>${atlassian.spring.scanner.version}</version>
            <scope>compile</scope>
        </dependency>
```

The files above are the file pom.xml from jar file available on Atlassian marketplace.
Could you please help us with the  configuration for these plugins and fix it ? 
Thanks!

**Comment by focbenz** [comment]
So far the scope for atlassian-spring-scanner-annotation has always been set to compile even during the latest changes.

Just some more analysis into the pom.xml changes for versions around 1.15
The major rework in "Allure for Bamboo" 1.15 changed the atlassian.spring.scanner.version from 1.2.13 to 2.1.7
This change in atlassian.spring.scanner.version was also reverted back to 1.2.13 in [version 1.16](https://github.com/allure-framework/allure-bamboo/compare/1.15.0...1.16.0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) wieder reverted.

A similar issue described in #288 mentioned that a downgrade to version 1.14 helped if you cannot upgrade or test newer version like 1.16.x

**Comment by vbragin** [comment]
Try to use 1.19.1 version (without S.S)
