### ISSUE TITLE
Bamboo 6.1.1 remote agents allure support

### ISSUE THREAD

**Issue by nikitalishin** [allure-framework/allure-bamboo#30]
Hey, everyone!
Is it possible to use remote agents to generate allure reports in Bamboo 6.1.1?
I tried to add executable capability Allure report to the remote agent. 
Install allure locally and set path in capability.
error was: 
`Error creating bean with name 'io.qameta.allure.********.AllureReportTask': Unsatisfied dependency expressed through constructor argument with index 0 of type [io.qameta.allure.********.AllureSettingsManager]: : No qualifying bean of type [io.qameta.allure.********.AllureSettingsManager] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.qameta.allure.********.AllureSettingsManager] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}`

**Comment by koenpeeperkorn** [comment]
Hi,

We are experiencing the same problem. Is this a configuration issue?

Thanks

**Comment by smecsia** [comment]
@nikitalishin @koenpeeperkorn please provide more information. Which version of Allure Bamboo plugin are you using? How did you set up and configure the plugin?

FYI: Latest Allure Bamboo plugin is not using the AllureReportTask anymore. It is advised to use the plan-level configuration and the "Allure Report" tab in the results.

**Comment by nikitalishin** [comment]
@smecsia 
Allure bamboo plugin v.1.4
Bamboo server 6.1.1
Centos 7.0
Postgresql-9.5
What are you mean about setup and configuration plugin? If you talk about [this](https://docs.qameta.io/allure/latest/#_bamboo) - yes its configured. and work perfectly at local agents.
Yes, I know that last allure plugin not using report task. But this issue about possibility use Allure report at remote agents. We can`t use local for this(( 

Thanx!

**Comment by smecsia** [comment]
@nikitalishin thanks for the provided info. 
When you're saying you can't use "local" for generating the report, do you mean that you don't want to use the plan-level configuration and for some reason can't use the environment of Bamboo server to store the reports?  And also you don't want to use "Allure Report" tab in the build results. Did I get it right? Would you be able to provide more details about the reason?

In fact Alllure Bamboo plugin 1.4 broke AllureReportTask, so you should not use it with the newer Allure Bamboo plugin. It is actually planned for removal.

**Comment by eroshenkoam** [comment]
@nikitalishin Plan settings will solve the problem

**Comment by eroshenkoam** [comment]
Feel free to reopen this issue
