### ISSUE TITLE
No report is generated Allure

### ISSUE THREAD

**Issue by dragichv** [allure-framework/allure-bamboo#32]
Hi!!
Installed the plugin "Allure for Bamboo" on the Bamboo server according to the instructions - https://docs.qameta.io/allure/latest/#_bamboo. But when I try to generate a report, I get an error:

```
> Failed to execute the build 'JST-IS-JOB1-110'
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.qameta.allure.bamboo.AllureReportTask': Unsatisfied dependency expressed through constructor argument with index 0 of type [io.qameta.allure.bamboo.AllureSettingsManager]: : No qualifying bean of type [io.qameta.allure.bamboo.AllureSettingsManager] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.qameta.allure.bamboo.AllureSettingsManager] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray (ConstructorResolver.java:749)
>         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor (ConstructorResolver.java:185)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor (AbstractAutowireCapableBeanFactory.java:1139)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance (AbstractAutowireCapableBeanFactory.java:1042)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean (AbstractAutowireCapableBeanFactory.java:504)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory.java:476)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory.java:342)
>         at sun.reflect.GeneratedMethodAccessor36.invoke (Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke (Unknown Source)
>         at java.lang.reflect.Method.invoke (Unknown Source)
>         at com.atlassian.plugin.osgi.spring.DefaultSpringContainerAccessor.createBean (DefaultSpringContainerAccessor.java:97)
>         at com.atlassian.plugin.module.ClassPrefixModuleFactory.createModule (ClassPrefixModuleFactory.java:35)
>         at com.atlassian.plugin.module.PrefixDelegatingModuleFactory.createModule (PrefixDelegatingModuleFactory.java:88)
>         at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.createModule (AbstractBambooModuleDescriptor.java:30)
>         at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.access $ 000 (AbstractBambooModuleDescriptor.java:17)
>         at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor $ 2.call (AbstractBambooModuleDescriptor.java:104)
>         at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode (BambooPluginUtils.java:132)
>         at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.getModule (AbstractBambooModuleDescriptor.java:113)
>         at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks (TaskExecutorImpl.java:285)
>         at com.atlassian.bamboo.task.TaskExecutorImpl.execute (TaskExecutorImpl.java:122)
>         at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call (ExecuteBuildTask.java:74)
>         at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build (DefaultBuildAgent.java:215)
>         at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl $ 1.call (BuildAgentControllerImpl.java:139)
>         at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl $ 1.call (BuildAgentControllerImpl.java:130)
>         at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor (CustomVariableContextImpl.java:221)
>         at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild (BuildAgentControllerImpl.java:129)
>         at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent $ 1.run (DefaultBuildAgent.java:137)
>         at com.atlassian.bamboo.utils.BambooRunnables $ 1.run (BambooRunnables.java:51)
>         at com.atlassian.bamboo.security.ImpersonationHelper.runWith (ImpersonationHelper.java:31)
>         at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority (ImpersonationHelper.java:20)
>         at com.atlassian.bamboo.security.ImpersonationHelper $ 1.run (ImpersonationHelper.java:52)
>         at java.lang.Thread.run (Unknown Source)
> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [io.qameta.allure.bamboo.AllureSettingsManager] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException (DefaultLis
```

What is the problem ? Thanks for the help !

**Comment by smecsia** [comment]
@dragichv You must be using the "old" approach of Allure report generation. Can you provide more details on how you set up your job? If you used the "Allure Report" task within the job - this is the old way of configuration. And the documentation does not list it anymore, while the Bamboo plugin itself still contains it though.

**Comment by dragichv** [comment]
Version of the plugin "Allure for Bamboo" - 1.4
Version "allure-commandline.zip" - 2.3.5
The plugin configuration is as follows (attach)
"You must use the" old "approach to generating Allure reports." - what do you mean. Do not get to describe in more detail how to do this?
Thanks for the answer!
![1](https://user-images.githubusercontent.com/22543200/30800675-927a444e-a202-11e7-9aff-29d6e735ee74.png)
![2](https://user-images.githubusercontent.com/22543200/30800680-96691a94-a202-11e7-8372-2672c3fd94bd.png)

**Comment by smecsia** [comment]
@dragichv According to your first screenshot, you're trying to build the report using the Allure Report task in a job, which is broken in the latest Allure Bamboo plugin. The new approach is described in the docs, you don't need to add an additional task in the job, you just need to specify the Allure artifacts to be picked up in the job by specifying the correct pattern like `**/allure-results/**` and then tick the `Enable Allure Building` box in the plan configuration on "Miscellaneous" tab. Please refer the new docs to configure it right.

**Comment by robertgates55** [comment]
@smecsia - I don't believe the specifying of the Allure artifacts to be picked up is described in the docs (not these ones anyway - https://docs.qameta.io/allure/latest/#_bamboo) - does the configuration of the artifact make a difference?

**Comment by dragichv** [comment]
I also do not quite understand where this is described in the documentation, without using a separate task

**Comment by smecsia** [comment]
@robertgates55 you're right, it is not described at the moment. I've recently sent a [PR](https://github.com/allure-framework/allure-docs/pull/72) to fix this.

**Comment by robertgates55** [comment]
Great thanks - I can confirm that the following config has resolved the issue for me:
![image](https://user-images.githubusercontent.com/7437497/30913909-b63c6e7e-a389-11e7-8af5-357fdd7f2eaa.png)

**Comment by dragichv** [comment]
how it looks to me for allure 2.2.1 (Something went wrong with the generation of the Allure report.) Here are some details:
java.lang.RuntimeException: The Allure executable could not be found by the name allure-2.2.1), if I installed version 2.3.5 and specified the path in the Path policy

**Comment by dragichv** [comment]
![image](https://user-images.githubusercontent.com/22543200/31008784-201ee42c-a527-11e7-96f0-521f851664c5.png)

**Comment by dragichv** [comment]
![image](https://user-images.githubusercontent.com/22543200/31008821-39ac6478-a527-11e7-8626-d6888b1215d8.png)

**Comment by dragichv** [comment]
![image](https://user-images.githubusercontent.com/22543200/31008839-4a7ac042-a527-11e7-9d93-6faf01df79b2.png)

**Comment by dragichv** [comment]
![image](https://user-images.githubusercontent.com/22543200/31008873-62acb166-a527-11e7-9be0-14e5be82f554.png)

**Comment by smecsia** [comment]
@dragichv Allure Bamboo is currently using the approach of building the report on Bamboo server, not on the agents. So you don't need to specify the requirements for the agents. 
Please refer [the docs](https://docs.qameta.io/allure/latest/#_bamboo) to specify the Allure executable capability and make sure that the Allure executable is available on your Bamboo server (as specified by the path in the capability). Capability has to be named properly, executable label should contain the version you'd like to use, e.g. "Allure 2.3.5", where "2.3.5" is the version you want to execute.
You can also let the plugin to download the executable automatically for you. To do this, you need to tick the "Download if no executable present' box in the configuration.
My suggestion for your particular case would be to:
1. Remove all Allure executables from Bamboo server
2. Remove all Allure capabilities from the Bamboo Server configuration
3. Reinstall Allure Bamboo plugin
4. Open the Bamboo Server capabilities list and make sure that it contains the "Allure Report" capability (any version)
5. Open "Allure Report" admin menu and make sure that "Download if no executable present" box is checked
6. Open your plan configuration and make sure that you have enabled "Enable Allure Building" checkbox on the "Miscellaneous" tab of your plan
7. Make sure you've specified the Allure artifacts to be picked up by your job
8. Run your job and verify that "Allure Report" tab is showing the built report

In case of any problems, refer the Bamboo server logs.

**Comment by dragichv** [comment]
@smecsia откатил плагин до версии 1.3. Для формирования использую отдельную таску через ваш плагин. Сам командлайн закинул на сервер бамбу, создал executable. Сборка артифакта проводится на агентах, затем артифакт расшаривается и во втором stage формируется отчет. Спасибо за помощь !!!
