### ISSUE TITLE
Reports aren't displayed on a bamboo build page due to the conflict with X-Frame-Options

### ISSUE THREAD

**Issue by tomkeiev** [allure-framework/allure-bamboo#332]
Bamboo v9.3.4 build 90306
Allure Bamboo plugin v1.17.0
On a build results page, the report can't be displayed. There is an error in the console saying:
"Refused to display 'https://bamboo.mydomain.com/' in a frame because it set multiple 'X-Frame-Options' headers with conflicting values ('ALLOWALL, SAMEORIGIN, SAMEORIGIN'). Falling back to 'deny'."
Some Chrome extensions can help by ignoring the X-Frame-Options header but it resolves the issue only locally and not for all people who want to see the report.
<img width="1907" alt="bamboo plugin x-frame options" src="https://github.com/allure-framework/allure-bamboo/assets/19896146/5c1af73d-3cf1-4ef6-bfcf-c8b44fc52bd3">

**Comment by vbragin** [comment]
Please try 1.19.1 version
