### ISSUE TITLE
allure creating folders of 18mb consuming bamboo temp space

### ISSUE THREAD

**Issue by NTVI-sys** [allure-framework/allure-bamboo#341]
We have recently started using the plugin for bamboo, and have encounter that it creates 18mb files full of .jar components requiring us to keep deleting the temp folder in bamboo which has grown to 200GB. 
Colleagues have took the effort to move the reports themselves to a different drive, but still the temp is filling up, any advice would be highly appreciated. 
Attaching a few screenshots. 
  
Thank you in advance for the support! 
![allure](https://github.com/user-attachments/assets/24eabc80-3e90-44da-8762-d3af1c58f1e6)

**Comment by NTVI-sys** [comment]
After the update to Version: 1.19.0, we are still seeing the 18mb folders in the bamboo temp being created, but not cleanup after the report is generated:
![image](https://github.com/user-attachments/assets/d4005af7-345d-498c-8127-610283ea4f0c)
![image](https://github.com/user-attachments/assets/ba9bc6ca-148f-4192-adab-dff54b5e01fe)

**Comment by vbragin** [comment]
Hello @NTVI-sys 
There was a problem that allure execution downloaded every time even it was already download.
Could you clean up the tmp folder and check if it will grow after several report generating.

**Comment by NTVI-sys** [comment]
Hello it is exactly what we did it was a clean 0byte folder yesterday, but will keep monitoring for several days

**Comment by vbragin** [comment]
Hello @NTVI-sys 
Try to use 1.19.1 - I added better cleanup for tmp folder
