### ISSUE TITLE
Failed to find Allure executable by name allure-2.30.0 using Bamboo

### ISSUE THREAD

**Issue by raphaelbaqueta** [allure-framework/allure-bamboo#343]
I’m encountering an issue when trying to use Allure version 2.30.0 with Bamboo Datacenter version 9.2.17 build 90216. 
Despite following all the recommended steps from the official documentation, I keep receiving the error message "Failed to find Allure executable by name allure-2.30.0" in the Allure Report tab after my build completes.

I’ve attempted to configure Allure both in the server capabilities and on the remote agent, but neither approach has worked. 
I would really appreciate your assistance in resolving this issue.

Thank you in advance for your time and support!

**Comment by vbragin** [comment]
Hello @raphaelbaqueta is the problem still exists?

It is difficult to understand why it is so from your description.

Could you provide more information.

As a possible reason it could be:

On the first install there is no execution on your env, on the path specified in the "Executables" settings area
<img width="800" alt="image" src="https://github.com/user-attachments/assets/aaabef5a-40f2-4665-b8bb-41ba65568919">
, and plugin with try to download it from the url specified in "Allure Report" settings area
<img width="471" alt="image" src="https://github.com/user-attachments/assets/d2dac7b2-fe52-423d-94a4-fa1dad05ab18">

So, it could be possible that there is no connection between "your env" and "location from url" as a result you will have no executable by name

Solutions could be:
1) Check access and add access to call host from the "Allure Report" settings area;
2) Create new executable as server capabilities as described in 
https://allurereport.org/docs/integrations-bamboo/#_3-install-the-executable
you should download be yourself and put it into the specified path with structure for example:
| tmp
       | - allure
                 | -- 2.30.0
                             | --- bin
                             | --- config
                             | --- lib
                             | --- plugins

**Comment by vbragin** [comment]
Looks like not relevant any more. If the issue still present we can reopen it.
