### ISSUE TITLE
Поддержка плагина для удаленных агентов

### ISSUE THREAD

**Issue by dragichv** [allure-framework/allure-bamboo#36]
Добрый день!!! 
Плагин хорош собой, но хотелось бы чтобы он работал и на удаленных агентов, а не только для локальных агентов. Будет ли такая реализация?

**Comment by eroshenkoam** [comment]
Привет, он работает на удаленных агентов, я не успел обновить инструкцию. 
Попробуй вот так и все заработает: https://docs.qameta.io/allure/latest/#_bamboo

**Comment by dragichv** [comment]
Артем, по той инструкции, что ты скинул, выполняется настройка для локального агента:
...."add an executable as a server capability".... . Может я чего-то не догоняю ? Также, из прошлого моего вопроса, была выяснено, что для бамбу версия плагина 1.4  не работает ? Так как мне ставить его для удаленного агента?? Сейчас версия инструкции 2.0.

**Comment by eroshenkoam** [comment]
@dragichv есть два способа для генерации отчета: 
1. Это таска в Job. Этот способ **устаревший**. Bamboo дает очень мало возможности таким плагинам, по-этому там ничего не работает. 
2. Это настройка Allure отчета для всего плана. В этом случае тебе нужно выполнить следующие действия: 
  * настроить экзекьютабл как показано в инструкции
  * настроить архивацию результатов allrue в каждой джобе
  * удалить генерацию Allure отчета в джобе
  * Зайти во вкладку Miscellaneous в настройках Allure и включить генерацию отчета для всего запуска. 
В таком случае отчет будет генерироваться на мастере для всех джоб внутри плана. В этом случае мы имеем больше возможностей, например, доступ к истории.

**Comment by eroshenkoam** [comment]
@dragichv Ты пробовал действовать по инструкции или нет?

**Comment by dragichv** [comment]
@eroshenkoam Привет!! 
`настроить экзекьютабл как показано в инструкции` - в инструкции описано как настраивать экзекьютабл для сервера (new executable server capability) или я могу настроить экзекьютабл и на удаленном агенте ?

**Comment by dragichv** [comment]
1. Создал на удаленном агенте экзекьютабл : 
![image](https://user-images.githubusercontent.com/22543200/31889472-ca79978e-b821-11e7-9127-f1f2e658f6b8.png)
2. стэйдж сборки артифакта. после сборки расшарил артифакт: 
![image](https://user-images.githubusercontent.com/22543200/31889585-26a7834a-b822-11e7-908c-fbe580046e96.png)

3. План настроен: 
![image](https://user-images.githubusercontent.com/22543200/31889707-9261fd86-b822-11e7-919e-d2a9276fc7b6.png)

**Comment by dragichv** [comment]
План выглядит следующим образом:
![image](https://user-images.githubusercontent.com/22543200/31889986-70c0168a-b823-11e7-8df5-7bde53d0c7f7.png)

![image](https://user-images.githubusercontent.com/22543200/31889999-8012d762-b823-11e7-91be-794ca8d90440.png)
