### ISSUE TITLE
bamboo 6.2.1 compatibility

### ISSUE THREAD

**Issue by h17liner** [allure-framework/allure-bamboo#37]
Hello
Allure plugin is compatible with bamboo 6.1.4 at this moment. Is it possible to build allure plugin compatible with bamboo version 6.2.1?  Thanks

**Comment by eroshenkoam** [comment]
<img width="1062" alt="2017-10-16 12 52 53" src="https://user-images.githubusercontent.com/781455/31606168-0ae52588-b271-11e7-92be-2ae760144878.png">
