### ISSUE TITLE
Поддержка плагина для удаленных агентов

### ISSUE THREAD

**Issue by dragichv** [allure-framework/allure-bamboo#39]
Добрый день!! Не могли бы вы предоставить руководство по настройке плагина для бамбу на удаленных агентах? В текущем руководстве описывается настройка плагина для локальных агентах на сервере бамбу. К сожалению по данному запросу - https://github.com/allure-framework/allure-bamboo/issues/36, ответа пока не получил, но, наверное и не получу, т.к задача закрыта. 

Спасибо!!!

**Comment by CrazyMoonkin** [comment]
Плагин работает на локальных и на удаленных агентах, но executable capability нужно настраивать глобальный - для самого bamboo-сервера, а не для агента.
Плагин ничего не делает на агентах, он генерирует отчет на основе артефакта с файлами allure.

P.S. решил написать, т.к. встретил случай неправильной настройки и ссылку на на эту задачу, как подтверждение того, что плагин не работает.
P.P.S. надеюсь кому-то это будет поможет.
