### ISSUE TITLE
Allure2 report doesn't generating trend , history, environment in bamboo

### ISSUE THREAD

**Issue by ezwanharun** [allure-framework/allure-bamboo#43]
I already create a bamboo job and downloaded the bamboo plugin (1.6 version) and Allure executables (2.5 version) on my bamboo server. Allure report was able to generated when I run my job. However there is no trend , environment, executor been automatically generated. I do noticed from other discussion mention that do need to put history folder into specific path but i noticed that  my history folder at diff location. I already create another artifact to grab both folder location. However I still wont be able to display the env,trends etc. 

  Here I defined the location of both history folder and allure-results folder.
<img width="1066" alt="screen shot 2018-01-09 at 10 33 44 pm" src="https://user-images.githubusercontent.com/13920802/34725861-35c2d53e-f58d-11e7-97fe-cbd269960be5.png">

where my results path is
`/bamboo-home/...../allure-results/*`

while my report was generated at 
`/opt/atlassian/....../allure-reports/JOBnumber/history/*`

Did I configure wrongly to catch those history folder?How do I grab both folder to display in allure report?

**Comment by keiru13** [comment]
@smecsia , @baev , @eroshenkoam  could you guys assist me on this. i know this one just a misconfigure the ../allure-reports path that contained the history file.

**Comment by keiru13** [comment]
I already figure out that allure for bamboo plugin doesn't copy .../allure-report/history/* files into .../allure-results folder in order to generate the trend graph. 

I using allure for bamboo version 1.6

**Comment by smecsia** [comment]
@keiru13  thanks for your research, I'll take a look at this soon.

**Comment by keiru13** [comment]
sure @smecsia . This the behaviours that I found. 
-no history folder(previous build) been copy into allure-results folder on new build.
-I created a script to copy over the history folder, then I found that the report generation doesn't append the content inside the history-trend.json file. Think that it still behave like first job been trigger.

**Comment by lucyily** [comment]
@smecsia The same issue as @ezwanharun mentioned in allure plugin for bamboo v1.7, no history and retries are added to the report

**Comment by artemryazantsev** [comment]
ping

**Comment by ankitkgupta09** [comment]
The same issue is applicable for Jenkins as well? History is not displayed correct data with Jenkins.
