### ISSUE TITLE
Allure Plugin for Bamboo can't generate the html 

### ISSUE THREAD

**Issue by c13** [allure-framework/allure-bamboo#45]
После окончания задания плагин не генерирует отчеты
```
Something went wrong with Allure Report generation. Here are some details: 
Build result does not have any uploaded artifacts!
```

Описаниние задание в Bamboo

- Создаю report c помощью behave на локальном агенте
`behave -f allure_behave.formatter:AllureFormatter -o ./report ./features/01index.feature"`
-  Репорт складываются в артефакт, как указано в шаге 7 документации
![allure](https://user-images.githubusercontent.com/1741510/40427727-32db6f24-5ea7-11e8-9229-0045fb6a7038.PNG)

-  В 5 шаге документации указано
`you may want to select the specific name of the artifact with the Allure results, which Allure Bamboo plugin will use`
 Это тоже выполнено и генерация отчетов включена
https://imgur.com/a/kEtelwS

**Comment by c13** [comment]
[5880800d-20fa-4e03-be3c-26200cfd05cb-result.zip](https://github.com/allure-framework/allure-bamboo/files/2031806/5880800d-20fa-4e03-be3c-26200cfd05cb-result.zip)

[bamboo.log](https://github.com/allure-framework/allure-bamboo/files/2031798/bamboo.log)

**Comment by smecsia** [comment]
Похоже, что артефакты не находятся при попытке их скачать. 
Какую версию Bamboo используете и версию Allure Bamboo плагина?
Также вопрос - используется удалённый агент или локальный? И включен ли ArtifactHandlers (например, для сохранения артефактов в S3)?

**Comment by c13** [comment]
ArtifactHandlers не включен
локальные агенты, ограничено с помощью Agent capabilities
![agent](https://user-images.githubusercontent.com/1741510/40474291-4c2c2eaa-5f47-11e8-9e2d-69d3eb7548b8.PNG)

Allure 2.6.0
Allure for Bamboo 1.7.0
Atlassian Bamboo version 5.15.5 build 51518

**Comment by smecsia** [comment]
К сожалению, не смог воспроизвести. Взял ваш файл с результатами, в сборке подкладываю его в директорию ./allure-results. 

Вот как выглядит artifact definition:
![image](https://user-images.githubusercontent.com/214657/40488812-f5f0e8c8-5faa-11e8-897f-b0500a6db93e.png)

Использую ту же версию плагина:
![image](https://user-images.githubusercontent.com/214657/40488874-13da7066-5fab-11e8-98cf-7285b975f838.png)

Использую ту же версию Bamboo: 
![image](https://user-images.githubusercontent.com/214657/40488894-202f8ebe-5fab-11e8-9e9e-4dbdec4f26e1.png)

Получаю на выходе отчёт:
![image](https://user-images.githubusercontent.com/214657/40488788-e8fbeba4-5faa-11e8-9662-bad976cdf83f.png)

**Comment by c13** [comment]
Можете прислать скриншот конфигурации плана - вкладка Miscellaneous?

**Comment by smecsia** [comment]
Так, а про Docker это уже интересно. Подозреваю, что проблема именно в этом. Что вы используете для запуска тестов в контейнерах?

**Comment by c13** [comment]
Спасибо, разобрался. Не срабатывал Allure Report в Build plans, которые были созданы до установки плагина и настроки Executable (или были склонированы со старых). Теперь работает и с docker, и c remote agent, и даже одновременно.
Надо добавить в документацию. После установки плагина, нужно создать новые планы с Allure report, чтобы он стабильно работал.

**Comment by smecsia** [comment]
Looks like the issue has been resolved.
