### ISSUE TITLE
Does this plugin support Xunit format? 

### ISSUE THREAD

**Issue by sscaff1** [allure-framework/allure-bamboo#52]
My Bamboo build plan outputs results in XUnit format, and I have a task with the XUnit parser parsing those results. So my tests run fine and produce an artifact with the xml; however, my allure report is not generated. Does the bamboo plugin support xunit format?

**Comment by vbragin** [comment]
Bamboo plugin use allure execution to generate report, please ask your question there:

https://github.com/allure-framework/allure2
