### ISSUE TITLE
Error when I run the build: Could not find default Allure executable! Please configure plugin properly!

### ISSUE THREAD

**Issue by cerebellum13** [allure-framework/allure-bamboo#55]
Good day! I set up the Allure plugin for Bamboo and encountered the following error:
![image](https://user-images.githubusercontent.com/19388630/58546830-e08cfd00-820e-11e9-93ba-58f8c8dc433d.png)

Tell me, what can it be connected with? I run the build on a remote agent (Win Server 2012). I myself use Bamboo version 6.9.0 (CentOS). And also I use the latest version of plugin (1.8.0). Executable of allure on remote agent:
![image](https://user-images.githubusercontent.com/19388630/58547025-45e0ee00-820f-11e9-8237-6d6320069871.png)

Allure is placed on:
![image](https://user-images.githubusercontent.com/19388630/58547072-63ae5300-820f-11e9-9322-221e7c70617b.png)

I've tryied:
C:\allure-2.7.0
C:\allure-2.7.0\bin
C:\allure-2.7.0\bin\allure.bat

No difference..

![image](https://user-images.githubusercontent.com/19388630/58547379-eb945d00-820f-11e9-82df-105cfcb50768.png)

![image](https://user-images.githubusercontent.com/19388630/58547414-f949e280-820f-11e9-8905-3a1b8dfa9faa.png)

In my project folder I have this structure:
![image](https://user-images.githubusercontent.com/19388630/58547502-226a7300-8210-11e9-95f9-381069ac8fbc.png)

AB-ABDP-JOB1 - is the root of my Project's build.

**Comment by CrazyMoonkin** [comment]
Hey!
You need to add executable in server capabilities, not in agent capabilities.

**Comment by cerebellum13** [comment]
I added executable for my server and it doesn't help me. Maybe problem with difference between OS of my server and agent?
