### ISSUE TITLE
allure plugin failed to download Allure of version 2.8.0 and high

### ISSUE THREAD

**Issue by destomir** [allure-framework/allure-bamboo#56]
I want to use allure-commandline of version 2.12.0, but allure plugin failed to download Allure of version 2.12.0, because Allure plugin create url to download: https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.12.0/allure-2.12.0.zip

I think, problem in method buildAllureDownloadUrl of class AllureDownloader. 
Method buildAllureDownloadUrl create url  look like **baseUrl + version + "/" + "allure-" + version + ".zip"**, but beginning of version 2.8.0 url like: https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.8.0/allure-commandline-2.8.0.zip

**Comment by krmahadevan** [comment]
@destomir - Please upgrade to the latest version of the allure bamboo plugin. I recently fixed this issue.

You also would need to adjust the download URL from 

`https://dl.bintray.com/qameta/generic/io/qameta/allure/allure`

to

`https://dl.bintray.com/qameta/maven/io/qameta/allure/`

in your allure reports configuration in Bamboo administration

**Comment by destomir** [comment]
@krmahadevan 
It's work! Thank you :)
