### ISSUE TITLE
Not obviously local path for allure-commandline

### ISSUE THREAD

**Issue by destomir** [allure-framework/allure-bamboo#57]
If i can't download allure-commandline of version 2.12.0 (https://github.com/allure-framework/allure-bamboo/issues/56), i tried to use executable path.

For use executable path, i download allure-commandline of version 2.12.0 and unpack. 
In server, i should have create the folder <allure-home>/binary and copy all files and folders from allure-2.12.0 to  <allure-home>/binary. Then set executable path <allure-home> in bamboo server.

I think, problem in method **provide** of class **AllureExecutableProvider**: 
allureHomeSubDir = Paths.get(allureHomeDir, **BINARY_SUBDIR**).toString()
final Path cmdPath = Paths.get(allureHomeSubDir, **"bin",** getAllureExecutableName());

**Comment by destomir** [comment]
It's problem, if put allure-commandline manual to bamboo server.
If allure-commandline download automaticaly, allure-bamboo-plugin will unpack downloaded zip to <executable_path>/binary. Then start from upacked directory

**Comment by vbragin** [comment]
for versions >= 2.13.1
Try to change the "Allure binary base url" to https://github.com/allure-framework/allure2/releases/download/
For versions <= 2.13.0
Try to change the "Allure binary base url" to https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline

If you install it manually set the execution path to:
/some/path/
And make sure that the full path will be like:
/some/path/binary/bin/allure
