### ISSUE TITLE
Can you configure reports to be generated & viewed on a job basis? 

### ISSUE THREAD

**Issue by bleepity** [allure-framework/allure-bamboo#59]
I just wanted to confirm this is not currently possible.

This feature would be helpful. Also, is it something that might be implemented in the future?

**Comment by smecsia** [comment]
Hi @bleepity, sorry for a long response. You're right, this is not currently possible, and current approach was intentional, because it allows you to run many jobs in parallel and then look into the overall report.
Why is this feature important for you?
P.S. we always appreciate any contributions

**Comment by bleepity** [comment]
We are using a bamboo plan, that contains many jobs, which can result in hundreds of reports. It is not convenient to view all the reports at once, when we just want to see the reports per job. It is important for us to have them grouped, and easily accessible instead of having to search through all of them just to find the one you want.

**Comment by DJ-QA** [comment]
We're looking into implementing Allure reports and have the same setup with Bamboo with many jobs.  We're providing reporting for departments in a college and having the ability to generated & viewed on a job basis would be easier for departments to view their results versus the general overview of all reports.
