### ISSUE TITLE
Please add support for Bamboo deployment plan

### ISSUE THREAD

**Issue by sahas-** [allure-framework/allure-bamboo#8]
I understand Allure supports many frameworks including a lot of unit testing frameworks. Specifically talking about functional testing support, these are typically executed post deployment part of the delivery pipeline. Recent Bamboo versions started supporting this idea better where we could use Bamboo deployment plans as a pipeline orchestrator that 
- provision dynamic infrastructure
- deploy the application either using Bamboo or scripts or delegate to another deployment tool 
- run acceptance/smoke/regression tests
- promote based on the previous step

Given this setup, it'll be nice to have Allure show up in bamboo "deployment tasks" and a way to navigate to test reports from the deployment project/environments. Please consider adding this support.

**Comment by vania-pooh** [comment]
@sahas- any pull requests are welcome. :)
