### ISSUE TITLE
Ошибка "Illegal char <:> at index 2" при выводе отчета в Bamboo

### ISSUE THREAD

**Issue by dmabramov** [allure-framework/allure-bamboo#88]
Добрый день!
Пытаюсь настроить плагин "Allure for Bamboo"
Bamboo version 6.9.1 build 60910 - 04 Jun 19
Allure for Bamboo Version 1.10.0 • Released 2019-07-28

Установил плагин, выполнил следующие настройки:
![image](https://user-images.githubusercontent.com/56311973/66474860-d1f70200-ea9a-11e9-8846-0c3d25cb2f61.png)
![image](https://user-images.githubusercontent.com/56311973/66474936-f5ba4800-ea9a-11e9-8408-e4e49ebbbcda.png)

Установил такую настройку плана сборки:
![image](https://user-images.githubusercontent.com/56311973/66474998-1aaebb00-ea9b-11e9-8e95-2618ce8fc743.png)

После выполнения плана сборки:
на вкладке "Metadata":
![image](https://user-images.githubusercontent.com/56311973/66475093-53e72b00-ea9b-11e9-943f-12c3de98da8d.png)
![image](https://user-images.githubusercontent.com/56311973/66475135-66616480-ea9b-11e9-8567-ed0c188a0684.png)

При переходе на вкладку отчета такая ошибка:
![image](https://user-images.githubusercontent.com/56311973/66476567-99592780-ea9e-11e9-8fcd-135075471b6d.png)

Пытался по разному настраивать параметр "Allure local storage", ничего не помогает.
Подскажите пожалуйста, что я делаю не так. 

Далее текст ошибки:
Version: 6.9.1
Build: 60910
Build Date: 04 Jun 2019

Request information:
...............

java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Atlassian/Bamboo/temp/allure-reports/AVT-KCA/97/index.html
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)

**Comment by vadimg7** [comment]
I got same issue. I can open results in Microsoft Edge from local folder C:\Users\vadimg7\Documents\Bamboo\temp\allure-reports\allure-reports\TES-ALP\2\index.html, but when opening in Chrome or Firefox or IE - results "Loading" and never populate.

I am also getting same error in Bamboo java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/vadimg7/Documents/Bamboo/temp/allure-reports/allure-reports/TES-ALP/2/index.html
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)

I am using latest Bamboo with latest Allure add-in

**Comment by mrscylla** [comment]
Столкнулся с такой же ошибкой, кто нибудь нашел решение?

**Comment by dmabramov** [comment]
У меня есть подозрение, что на Windows это просто не работает.

**Comment by mrscylla** [comment]
> У меня есть подозрение, что на Windows это просто не работает.
Оно работает если в CMD allure open сделать. А вот именно через bamboo не хочет

**Comment by mrscylla** [comment]
Валится в файле: allure-bamboo/src/main/java/io/qameta/allure/bamboo/AllureReportServlet.java в процедуре setResponseHeaders. Убрал нормализацию пути Path.get() и заработало.

` private void setResponseHeaders(HttpServletResponse response, String fileUrl) throws IOException {

        try {
            response.setStatus(HttpServletResponse.SC_OK);
            final URI file = new URL(fileUrl).toURI();
            //final String mimeType = ofNullable(getServletContext().getMimeType(fileUrl)).orElse(Files.probeContentType(Paths.get(file.getPath())));
            final String mimeType = getServletContext().getMimeType(fileUrl);
            final String charsetPostfix = of("application", "text").anyMatch(mimeType::contains) ? ";charset=utf-8" : "";
            response.setHeader("Content-Type", mimeType + charsetPostfix);
            //response.setHeader("Content-Disposition", "inline; filename=\"" + Paths.get(file.getPath()).getFileName().toString() + "\"");
            response.setHeader("Content-Disposition", "inline; filename=\"" + fileUrl + "\"");

        } catch (URISyntaxException e) {
            // should never happen
            throw new RuntimeException(e);
        }
    }`

**Comment by bcexopolllo** [comment]
I think here is the similar issue I have in an thread I reported before, please take a look:
https://github.com/allure-framework/allure-bamboo/issues/48#issuecomment-544451106
Talk to Atlassian Bamboo support, they even suggest the line of code where it could be potentially fixed
