### ISSUE TITLE
Standalone Plugin

### ISSUE THREAD

**Issue by zebulon501** [allure-framework/allure-bamboo#9]
I wanted to try this plugin which seems promising, but as my bamboo server and build agents are not connected to the internet, the report can't be produced.
Can you please build a standalone version of this plugin, i.e. with all the dependencies included?
Thanks for your help.

**Comment by vania-pooh** [comment]
@baev: does allure-report-builder support offline mode for now? This plugin is currently using version 2.0 but the latest is 2.3.

**Comment by zebulon501** [comment]
Any news on the standalone plugin?
